# expenses/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ExpenseViewSet, ApprovalRuleViewSet, CountryListView # Import CountryListView

router = DefaultRouter()
router.register(r'expenses', ExpenseViewSet, basename='expense')
router.register(r'approval-rules', ApprovalRuleViewSet, basename='approval-rule')

urlpatterns = [
    # --- ADD THIS LINE ---
    # This creates the endpoint for http://127.0.0.1:8000/api/countries/
    path('countries/', CountryListView.as_view(), name='country-list'),

    # This includes the URLs generated by the router (like /expenses/)
    path('', include(router.urls)),
]